### ISSUE TITLE
Saving Video Crashes on Ubuntu 16.04

### ISSUE THREAD

**Issue by burningion** [actarian/vscode-glsl-canvas#1]
Thanks for the work!

Just wanted to let you know, saving a webm hangs Visual Studio Code in Ubuntu 16.04. 

I can record the video, but once I hit stop and the save dialog box comes up, Visual Studio Code hangs and I have to kill it.

**Comment by actarian** [comment]
Thank you, I'll try to fix it with the next release.

**Comment by actarian** [comment]
@burningion  I've tested the extension on a fresh installation in Ubuntu 16.04 but I do not experienced the issue. 

However this helped me resolve other problems related to other extension dependancy. I've tried to change the codec from `.webm` h264 to standard `.webm.`. 

You can try it downloading the `.vsix ` from [here](https://github.com/actarian/vscode-glsl-canvas/blob/master/glsl-canvas-0.1.4.vsix) and launching `Extensions: Install from VSIX...` from command palette.

**Comment by burningion** [comment]
That worked! The UI still gets wonky for me (mouse clicking doesn't work), but if I hit ENTER to accept, the file is successfully saved.

Thanks!
