### ISSUE TITLE
[QUESTION] a basic working vertex & fragment shader errors

### ISSUE THREAD

**Issue by lewislepton** [actarian/vscode-glsl-canvas#11]
now I may just be hitting my head against the wall, but im looking to do minor vertex shader stuff, alongside fragment & trying basic shaders for both is coming up with errors.

im trying different things from different sources, making sure that I have `attribute` & `varying` & making sure things are named right.

I have also tried playing with different things, but still running up with errors only on the vertex.

would be great if there was some info. but then again if vertex are not supported, which would be odd, then fair enough. but would be nice to see where my errors can lead to being fixed

thanks & all the best

here is the fragment code - which does not error
```
#ifdef GL_ES
precision mediump float;
#endif

uniform sampler2D texture0;

varying vec2 texCoord0;

void main(){
	gl_FragColor = texture2D(texture0, texCoord0.st);
}
```

this is the vertex code - which does error
```
uniform mat4 projection_matrix;
uniform mat4 modelview_matrix;

attribute vec3 a_Vertex;
attribute vec2 a_TexCoord0;
varying vec2 texCoord0;

void main(){
	vec4 pos = modelview_matrix * vec4(a_Vertex, 0.0);	

	texCoord0 = a_TexCoord0;

	gl_Position = projection_matrix * pos;
}
```

**Comment by actarian** [comment]
@lewislepton vscode-glsl-canvas extension support only fragment shader, 
the vertex shader is fixed with this code  

```
#ifdef GL_ES
precision mediump float;
#endif

attribute vec2 a_position;
attribute vec2 a_texcoord;

varying vec2 v_texcoord;

void main(){
    gl_Position = vec4(a_position, 0.0, 1.0);
    v_texcoord = a_texcoord;
}
```

if you want to customize your vertex shader please use the glslCanvas.js library at this link [https://github.com/patriciogonzalezvivo/glslCanvas](https://github.com/patriciogonzalezvivo/glslCanvas)

**Comment by lewislepton** [comment]
coolio, cheers man
