### ISSUE TITLE
Custom Uniforms Missing Values

### ISSUE THREAD

**Issue by willstall** [actarian/vscode-glsl-canvas#12]
Heyo!

I absolutely love this extension and use it constantly. I'd love to be able to use the custom uniforms, but they see to have a lot of value issues. I have my shader on my left panel and glslCanvas on my right panel. If I open up an shader that uses the custom uniforms the values are unset until I click on stats and manually change a uniform. Once I change a uniform we're golden. The second I click back to the code window...the values immediately null out. The custom uniforms also have no default value when entering a shader. Other uniforms like resolution and time work fantastic. I also have "glsl-canvas.timeout": 0 set.  Also to note: I don't have these issue with "glsl-canvas.textures".

Awesome work!! I am using this plugin for everyday shader daily's, so please let me know how I can help in any way!

**Comment by actarian** [comment]
@willstall issue has been fixed in latest release. thank you!
