### ISSUE TITLE
GLSL canvas disappears when reordering editor layout

### ISSUE THREAD

**Issue by Niels-NTG** [actarian/vscode-glsl-canvas#14]
When I want to preserve some horizontal space I move the GLSL canvas underneath my shader code. When I either do this by dragging the canvas tab to the lower/upper half of my editor or do "View" > "Editor Layout" > "Flip Layout", the tab becomes blank. Doing the "Refresh glslCanvas" action doesn't do anything. This used to work in earlier versions of VSCode. I'm not sure which version because it has been a while I've used this plugin.

**Comment by actarian** [comment]
@Niels-NTG issue has been fixed in latest release. thank you!

**Comment by Niels-NTG** [comment]
Yes, that indeed solved the issue. Thanks! 👍
