### ISSUE TITLE
All *.cpp files are treated as glsl.

### ISSUE THREAD

**Issue by Smilediver** [actarian/vscode-glsl-canvas#15]
After update to 0.2.2 all cpp files are being treated as glsl. If I downgrade to 0.1.92, everything is fine again.

**Comment by actarian** [comment]
@Smilediver Could you please try downloading version 0.2.3 .vsix from [here](https://github.com/actarian/vscode-glsl-canvas/blob/master/glsl-canvas-0.2.3.vsix) and launching Extensions: Install from VSIX... from command palette? If this solve your issue I'll proceed with a public release.
