### ISSUE TITLE
u_mouse and u_resolution

### ISSUE THREAD

**Issue by bryangingechen** [actarian/vscode-glsl-canvas#17]
Something is off with `u_mouse` and / or `u_resolution` on my computer. [The shader](https://thebookofshaders.com/edit.php?log=180219000427) you linked in issue #2 works fine for me in my browser, but when I try it with the extension in VS Code the dot is restricted to the bottom left quarter of the canvas:

![video clip](https://user-images.githubusercontent.com/5209952/52804632-ada16d80-3052-11e9-89ca-5f69cd74ee99.gif)

I'm on a macBook Pro with a retina display; could it be a devicePixelRatio issue?

**Comment by actarian** [comment]
@bryangingechen Could you please try downloading version 0.2.5 .vsix from [here](https://github.com/actarian/vscode-glsl-canvas/blob/master/glsl-canvas-0.2.5.vsix) and launching Extensions: Install from VSIX... from command palette? If this solve your issue I'll proceed with a public release.

**Comment by bryangingechen** [comment]
This works! Thanks so much!

**Comment by actarian** [comment]
@bryangingechen issue has been fixed in latest release. thank you!
