### ISSUE TITLE
Undeclared Identifier Basic Example

### ISSUE THREAD

**Issue by IanNS333** [actarian/vscode-glsl-canvas#18]
I just downloaded this extension and when trying to run any example found [here](https://actarian.github.io/vscode-glsl-canvas/) (https://actarian.github.io/vscode-glsl-canvas/) I get all sorts of syntax errors. As shown in the image below, can someone help me understand what is going on?

![image](https://user-images.githubusercontent.com/17051143/53726544-c754fa00-3e33-11e9-8e99-0dbe511ac191.png)

**Comment by actarian** [comment]
@IanNS333 You're simply missing some pieces of code. use the create button or copy/paste this code.

```

#ifdef GL_ES
precision mediump float;
#endif

uniform vec2 u_resolution;
uniform vec2 u_mouse;
uniform float u_time;

#define PI_TWO			1.570796326794897
#define PI				3.141592653589793
#define TWO_PI			6.283185307179586

vec2 coord(in vec2 p) {
	p = p / u_resolution.xy;
	// correct aspect ratio
	if (u_resolution.x > u_resolution.y) {
		p.x *= u_resolution.x / u_resolution.y;
		p.x += (u_resolution.y - u_resolution.x) / u_resolution.y / 2.0;
	} else {
		p.y *= u_resolution.y / u_resolution.x;
		p.y += (u_resolution.x - u_resolution.y) / u_resolution.x / 2.0;
	}
	// centering
	p -= 0.5;
	p *= vec2(-1.0, 1.0);
	return p;
}
#define rx 1.0 / min(u_resolution.x, u_resolution.y)
#define uv gl_FragCoord.xy / u_resolution.xy
#define st coord(gl_FragCoord.xy)
#define mx coord(u_mouse)

void main() {
	vec3 color = vec3(
		abs(cos(st.x + mx.x)),
		abs(sin(st.y + mx.y)),
		abs(sin(u_time))
	);
	gl_FragColor = vec4(color, 1.0);
}
					
```

You can also add code by snippets. Try start typing `glsl.main` and press enter.

more info [here](https://github.com/actarian/vscode-glsl-canvas/blob/master/src/snippets/snippets.md)
