### ISSUE TITLE
After resizing, u_mouse uniform reports wrong values

### ISSUE THREAD

**Issue by peeke** [actarian/vscode-glsl-canvas#2]
When I show the glslCanvas u_mouse uniform reports the correct values. When I resize the canvas window, or the whole vscode window, the u_mouse uniform reports incorrect values. 

I'm using this plugin on OS X 10.12.6, 15" inch macbook with retina screen (2.0 devicePixelRatio). VS  Code version is 1.20.1.

**Comment by actarian** [comment]
@peeke I can't reproduce the issue. could you please try with this fragment? [link](http://thebookofshaders.com/edit.php?log=180219000427)
