### ISSUE TITLE
[Question] Setting up IntelliSense

### ISSUE THREAD

**Issue by RobertAron** [actarian/vscode-glsl-canvas#20]
Hi! I just have a quick question about workflow. I'm really new to shaders so please excuse me if this is a dumb question :)

I noticed someone else was setting up intellisense in #10 and wanted to try it out as well. I included glm in my workspace and set my file name to be `helloworld.glsl.cpp`. In my file I have

```cpp
#ifdef _WIN32
#include <glm/glm.hpp>
using namespace glm;
#endif
```

This makes intellisense work, but it has some bad side effects like losing the color picker, and the cpp linter complaining that `uniform` is not a type name. I'm happy with my setup but it feels a tad hacky.

I'm just curious if this kind of setup is normal, or if maybe I'm missing something obvious.

**Comment by actarian** [comment]
@RobertAron unfortunately as of today the shader extensions are 
```
"extensions": [
          ".vs",
          ".fs",
          ".gs",
          ".comp",
          ".vert",
          ".tesc",
          ".tese",
          ".frag",
          ".geom",
          ".glsl",
          ".glslv",
          ".glslf",
          ".glslg"
],
```
.cpp files are handled by the editor as c++ files only.
