### ISSUE TITLE
is glsl version 3.0 and higher supported?

### ISSUE THREAD

**Issue by ianacaburian** [actarian/vscode-glsl-canvas#21]
```
out vec4 out_color;
void main() {
	out_color = vec4(1.0);
}
```
This tells me I need higher version, and then doesn't seem to work when I add `#version 300 es`. Thanks for your attention.

**Comment by rmmh** [comment]
Probably needs the equivalent of patriciogonzalezvivo/glslCanvas#37

**Comment by actarian** [comment]
@ianacaburian @rmmh could be trivial to handle both conditions, but vscode-glsl-canvas uses a customization of glslCanvas, I'll try to investigate through this.

**Comment by actarian** [comment]
@ianacaburian @rmmh WebGL2 support has been added to latest release of the extension. Thank You!
