### ISSUE TITLE
Incorrect color

### ISSUE THREAD

**Issue by winduptoy** [actarian/vscode-glsl-canvas#22]
I've noticed that the color is incorrect for me. A simple shader that renders solid red is not completely red in the rendered output. See the difference between the canvas and the color picker? Is there some sort of color space transformation going on here?

![Screenshot from 2019-05-15 15-26-46](https://user-images.githubusercontent.com/270504/57803260-f639f700-7725-11e9-9540-38781ca307cb.png)

**Comment by actarian** [comment]
@winduptoy Cannot reproduce, could be something that has to do with color space. (currently tested on mac and windows)

![Schermata 2019-05-20 alle 16 15 12](https://user-images.githubusercontent.com/1841442/58028310-bd7d9180-7b1a-11e9-8c10-0c9a760824ee.png)

**Comment by winduptoy** [comment]
Welp, shucks. This was on Ubuntu 19.04. Curse the complexity of the graphics stack.
