### ISSUE TITLE
no command Show glslCanvas available

### ISSUE THREAD

**Issue by mujina93** [actarian/vscode-glsl-canvas#28]
Installed the extension on Windows 10 1903. Using Ctrl-P and searching for "Show glslCanvas" does not provide any result. Am I missing something about the installation maybe?

**Comment by actarian** [comment]
@mujina93 this does not seems an extension issue. Did you try restarting vscode? Eventually, if you find the way to run incurring into other issues try to run `Developer: Toggle Developer Tools`.

**Comment by actarian** [comment]
closed due to inactivity.
