### ISSUE TITLE
Slow update time when changing values

### ISSUE THREAD

**Issue by leocb** [actarian/vscode-glsl-canvas#3]
The Book of Shaders Editor is notorious for it's fast update time when changing values
This extension seems to recompile the shader when the editor is in the "Idle" status rather than "on type"; Again, I don't know exactly how you implemented this or if this is a limitation of VSCode itself.

But I believe giving the user options is the best way to go, my suggestion is to create a command (F1) or setting (settings.json) to define when the compiler runs: on type | Idle

I think it would be nice to reach the original editor's speed, I'll take a look at their source code to see how they managed to get such speed.

If I get the time, I'll open a PR myself.

Thanks for the extension!

**Comment by actarian** [comment]
@leocb I'll look into it in the next release. I'll change the setTimeout with a throttle function.

**Comment by leocb** [comment]
[Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) Uses a bracketPairColorizer.timeOut configuration to let users set whatever timeout they want (0 to disable the timeout). I believe something like this would be sufficient.

**Comment by leocb** [comment]
@actarian I'm working on a PR for this, I've already added a configuration string to set the timeout, what would be better for the default value: 1000ms timeout or no timeout? I tested the "main" snippet with no timeout and the result was very good and responsive
