### ISSUE TITLE
The non-compact formatter enforces a space at the end of some lines

### ISSUE THREAD

**Issue by KoltesDigital** [actarian/vscode-glsl-canvas#33]
Hi,

Uncommenting https://github.com/actarian/vscode-glsl-canvas/blob/eded3004b3d1fb9b4fd88cc11b954210800e9f2c/src/glsl/format.provider.ts#L71 solves the problem, but I can't tell if it introduces other irregularities.

**Comment by KoltesDigital** [comment]
Hm, also when a line starts with `{`, a space is enforced before. But this may need a change in the algorithm.

**Comment by actarian** [comment]
@KoltesDigital issue has been fixed in latest release. thank you!

**Comment by KoltesDigital** [comment]
Great, thanks!
