### ISSUE TITLE
audio & webcam

### ISSUE THREAD

**Issue by weepy** [actarian/vscode-glsl-canvas#35]
would it be possible to have audio and webcam textures like ShaderToy ?

**Comment by actarian** [comment]
@weepy unfortunately vscode does not ship with ffmpeg so actually is not possible to play video or audio elements. [vscode/issues/67945](https://github.com/microsoft/vscode/issues/67945#issuecomment-461157831)

**Comment by weepy** [comment]
oh - I assumed it was webgl/javascript ?

**Comment by actarian** [comment]
@weepy yes it is, but the vscode app is shipped with a chromium version that is missing with the capability of playing video or audio elements. You can however try the export functionality that open your glsl code in your browser that doesn't have the restriction.
