### ISSUE TITLE
How to use webgl2 ?

### ISSUE THREAD

**Issue by constantdupuis** [actarian/vscode-glsl-canvas#36]
I don't find any information about using WebGl2 with glslCanvas. 
Nohting in STackOverflow.
I have read https://webgl2fundamentals.org/webgl/lessons/webgl-shaders-and-glsl.html, but I just got a white result with the following code 

```GLSL
#version 300 es

precision mediump float;

out vec4 outColor;  // you can pick any name
uniform vec2 u_resolution;
uniform float u_time;
 
void main() {
    // vec2 st = gl_FragCoord.xy / u_resolution.xy;
    // st.x *= u_resolution.x / u_resolution.y;

   vec3 color = vec3(0.3, 0.2, 0.0);

   outColor = vec4(color, 1.0);
}
```

If I use gl_FragColor I got a error message ...

What did I Miss ?

Thank's

Constant

**Comment by mic361** [comment]
Hi, Constant, by chance I had the same problem just a few hours later. I am using webgl2 as part of the Visual Studio Code glsl-canvas extension. Seems that the problem went away after restarting vscode, and then starting with a webgl2 based shader within vscode. In fact, webgl1 based shaders then showed compile errors. I started using the example from [glsl-canvas](https://github.com/actarian/glsl-canvas/blob/master/docs/shaders/example-20.glsl) which works fine that way.

**Comment by constantdupuis** [comment]
Yes it works now !? I'm sure I have restarted my computer ...
Thank you to pointing me to the samples.

Regards,

Constant
