### ISSUE TITLE
Looking for WebGL Extension Support

### ISSUE THREAD

**Issue by willstall** [actarian/vscode-glsl-canvas#38]
Hey team!

I'm looking to use texture2DLodEXT in a shader. I've added:
#extension GL_EXT_shader_texture_lod : enable
#extension GL_OES_standard_derivatives : enable

But, I believe we might need to add:
gl.getExtension('EXT_shader_texture_lod');

to our gl init for this to work. Am I doing something wrong or is this something we could easily add?

Here's the doc:
https://developer.mozilla.org/en-US/docs/Web/API/EXT_shader_texture_lod

Thanks!
Will

**Comment by actarian** [comment]
@willstall 
WebGL extensions has been added to extension version 0.2.10  
You can include any supported WebGL extension through the ```glsl-canvas.extensions``` array option modifying the workspace's ```settings.json``` file. 
```json
{
  "glsl-canvas.extensions": [
    "EXT_shader_texture_lod"
  ]
}
```
You can then enable the extension in the shader
```glsl
#extension GL_EXT_shader_texture_lod : enable  

vec3 color = texture2DLodEXT(u_texture, st, 0.0).rgb;
```
___
