### ISSUE TITLE
nested includes

### ISSUE THREAD

**Issue by BrendonCon** [actarian/vscode-glsl-canvas#41]
Hey guys, thanks for an awesome tool firstly :)

I wanted to query whether nested includes work? I keep getting a glsl-canvas error when I try nesting includes into files that are being included. Is there a way I can debug on my end to help? I'm looking to make a common lib and to have a lot of smallish functions in their own files.

Thanks again!

**Comment by actarian** [comment]
@BrendonCon thank you! 
Unfortunately at the moment nested includes are not available.
I'll try to investigate the possibility to add them.

**Comment by BrendonCon** [comment]
@actarian thanks so much, I can still work with that so all good :) Hopefully its not too much of a pain, good luck!

**Comment by actarian** [comment]
@BrendonCon latest version `0.2.12` now support nested includes with relative path. Thank you for your submission.

**Comment by BrendonCon** [comment]
@actarian thank you so so much! Updating now. Cheers
