### ISSUE TITLE
Load error for #include

### ISSUE THREAD

**Issue by zeroinformatique** [actarian/vscode-glsl-canvas#46]
I just added a simple `#include "common.glsl"` in my project, but I get an error with VSC:

> Load error: "Error: Network request failed for url vscode-resource:/e:/shaders/common.glsl"

The path and filenames are correct.
I'm on Windows 10 with VSC 1.50.1

**Comment by Anatta336** [comment]
I'm experiencing the same problem. Also on Windows 10 (64-bit) with Visual Studio Code 1.15.1. For a project in l:/Shaders with `#include "remap.glsl"` I receive the following error (there is a file at `l:/Shaders/remap.glsl`).

> Load error: "Error: Network request failed for url vscode-resource:/l:/Shaders/remap.glsl"

I have found a partial workaround. If I have another .glsl file open in Visual Studio Code and switch from that tab back to the main shader it correctly compiles a working shader that uses the `#include`. But as soon as I do anything to trigger a recompilation of the shader the same "Network request failed" fatal error occurs. Switching from a tab that contains some other non-glsl file doesn't work.

While I'm here, thank you for your work on this tool. It's very convenient to have this kind of preview suite available directly in the editor.

**Comment by gabehilism** [comment]
If you want to solve the problem without having to tab back and forth between open files, you can force the extension to re-render the webview like so at panel.ts (153):

`
	public update(uri?: vscode.Uri) {
		return this.render(uri);
	}
`

Not the best solution, but temporarily seems to get the job done.

**Comment by polyclick** [comment]
I'm encountering the same error on macOS Big Sur when trying to use `#include "file.glsl"`, I get an error:

```
Load error: "Error: Network request failed for url vscode-resource:/Users/polyclick/Dropbox/Projects/2021/2021.03.15-bookofshaders/test.glsl"
```

**Comment by actarian** [comment]
Latest version `0.2.12` now supports nested includes with relative path and better support for loading local resources. Thank you for your submission.

**Comment by polyclick** [comment]
Thank you sooo much! :) This resolves the problem I was having. Thanks!
