### ISSUE TITLE
WebGL2: IO buffers don't work if u_mouse isn't written somewhere

### ISSUE THREAD

**Issue by Azorlogh** [actarian/vscode-glsl-canvas#47]
This code produces a black image :
```glsl
#version 300 es
precision mediump float;
uniform vec2 u_resolution;
uniform vec2 u_mouse;
uniform sampler2D u_buffer0;
out vec4 outColor;

#ifdef BUFFER_0
void main() {
	outColor = vec4(1, 0, 0, 1);
}
#else
void main() {
	outColor = vec4(
		texture(u_buffer0, gl_FragCoord.xy / u_resolution.xy).rgb, 1.0
	);
}
#endif
```

But adding a completely random `//u_mouse` comment to the code fixes it:
```glsl
#version 300 es
precision mediump float;
uniform vec2 u_resolution;
uniform vec2 u_mouse;
uniform sampler2D u_buffer0;
out vec4 outColor;

#ifdef BUFFER_0
//u_mouse
void main() {
	outColor = vec4(1, 0, 0, 1);
}
#else
void main() {
	outColor = vec4(
		texture(u_buffer0, gl_FragCoord.xy / u_resolution.xy).rgb, 1.0
	);
}
#endif
```

**Comment by actarian** [comment]
@Azorlogh issue has been resolved in latest version `0.2.12`. Thank you for your submission.

**Comment by Azorlogh** [comment]
Strangely now both show a black screen for me :confused:

**Comment by actarian** [comment]
@Azorlogh this is weird, it works on MacOs but not on Windows. Need to investigate further.

**Comment by Azorlogh** [comment]
Oh I should specify I'm on linux with nvidia's proprietary drivers.

**Comment by actarian** [comment]
@Azorlogh  should be related to the version of Chrome (87) adopted by VsCode as occurred to the glTF Tools VsCode extension [here](https://github.com/google/filament/issues/3308). I'm updating the [glsl-canvas](https://github.com/actarian/glsl-canvas) lib.

**Comment by actarian** [comment]
@Azorlogh could you please check if these WebGL1 & WebGL2 [examples](https://actarian.github.io/glsl-canvas/buffer.html) work on your device?

**Comment by Azorlogh** [comment]
I tested them on chrome 90 and they both seem to work, I also tested in an embedded browser inside vscode and it works as well (in vscode whatismybrowser.com says my browser is "Headless Chrome 89")

**Comment by actarian** [comment]
@Azorlogh extension has been updated to version `0.2.13` with the new [glsl-canvas](https://github.com/actarian/glsl-canvas) lib.

**Comment by Azorlogh** [comment]
It works now! Thanks for this useful extension
