### ISSUE TITLE
Formatting != operator with the non-compact formatter

### ISSUE THREAD

**Issue by EnixCoda** [actarian/vscode-glsl-canvas#48]
The `!=` operator seems to be not correctly formatted when the `Use compact formatter` option is disabled in settings.

### Before formatting
```glsl
if (0 != 0){}
```

### After
```glsl
if (0 ! = 0) {}
```

And there is an error message in the output tab: `ERROR line 1    if      syntax error`

Thank you for this extension!

**Comment by actarian** [comment]
@EnixCoda issue has been resolved in latest version `0.2.12`. Thank you for your submission.
