### ISSUE TITLE
No reload until uniform u_time is used

### ISSUE THREAD

**Issue by sixclones** [actarian/vscode-glsl-canvas#5]
Hello

Since the last update, when I create a fragment shader, the preview doesn't update until I insert `u_time` in my code.

VSCode : 1.24.1
macOS : 10.13.5

Demo:
![glslcanvas-bug](https://user-images.githubusercontent.com/19307232/41794831-fb1681ec-7660-11e8-882d-cb3c53c15491.gif)

**Comment by actarian** [comment]
@sixclones Thank you, I've spotted some issue on a dependency. I'm going to fix that.

**Comment by actarian** [comment]
@sixclones Fixed with version 0.1.91
