### ISSUE TITLE
Docs: example how to load an .obj

### ISSUE THREAD

**Issue by polyclick** [actarian/vscode-glsl-canvas#50]
Hi

I can't seem to figure out how to load a custom `.obj`, can we get an example in the docs or playground on how to do this?

Thanks

**Comment by actarian** [comment]
Hi @polyclick, here you can find a working example:
https://github.com/actarian/glsl-canvas/blob/master/docs/shaders/example-basic.glsl

You should load the obj model by commenting the a_position attribute in the vertex shader.

Es.

#if defined(VERTEX)
attribute vec4 a_position; // data/dolphin.obj
...

**Comment by polyclick** [comment]
Thanks for the reply @actarian! I tried this but doesn't seem to work for me right now?

Here's my project structure & the first bit of the code. I'm trying to figure out what is wrong but I don't know where to look for error messages.

![my_glsl_—_loadmodel](https://user-images.githubusercontent.com/1213072/111646180-b81a2c80-8801-11eb-9e82-c8df53d20a5c.jpg)

**Comment by polyclick** [comment]
Thanks! This works :)
