### ISSUE TITLE
Flicker/stutter on update settings.json

### ISSUE THREAD

**Issue by mattorp** [actarian/vscode-glsl-canvas#51]
Is there a way to avoid this flickering on updating the settings.json? I'm currently updating it from an external script, and it would be nice for prototyping if this can be avoided.

https://youtu.be/YM7vl-MRYrM

**Comment by actarian** [comment]
@mattorp udating the settings.json on every nth frame could be an heavy task for vscode. maybe could be faster to update the glsl file itself, but even this involve accessing to the file system. the fastest way should be exporting the glsl with the export to html feature and update the uniform values via javascript.

**Comment by mattorp** [comment]
Writing to the glsl indeed solves the problem. Thank you @actarian !

**Comment by mattorp** [comment]
Example of an implementation:

```js
const fs = require('fs')
const replace = ({ path, searchValue, replaceValue }) => {
  const string = fs.readFileSync(path, 'utf-8')
  const newString = string.replace(searchValue, replaceValue)
  fs.writeFileSync(path, newString)
}

const searchValue = new RegExp('vec3 u_circle_0\ ?=\ ?vec3\(.+\);')
const replaceValue = 'vec3 u_circle_0 = vec3(0.0,0.0,0.0);'
const filename = '/scenes/2d-pong.synscene/main.glsl'
const path = __dirname + filename

replace({ path, searchValue, replaceValue })
const sleep = async ms =>
  await new Promise((resolve) => setTimeout(resolve, ms))

const iterations = 1000

const run = async () => {
  for (let i = 0; i < iterations; i++) {
    await sleep(3)
    const x = i * 1
    const y = i * 1
    const z = 30
    const replaceValue = `vec3 u_circle_0 = vec3(${x}.,${y}.,${z}.);`
    replace({ path, searchValue, replaceValue })
  }
}

run()
```
