### ISSUE TITLE
Texture error "u_texture_0": "./foo.jpg" since v0.2.12

### ISSUE THREAD

**Issue by TheMasterFX** [actarian/vscode-glsl-canvas#53]
I just updated GLSL Canvas to Version v0.2.12 from v0.2.11 and I now get the error 'Texture error "u_texture_0": "./foo.jpg"
![image](https://user-images.githubusercontent.com/12451336/114189638-b5b37a00-994a-11eb-8dd3-30708ee088fd.png)
When I downgrade to v0.2.11 everything works just fine

My VSCode Version info
```Version: 1.55.1 (user setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:06:02.360Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041`
```
my .vsocde/settings.json looks like this
```
{
"glsl-canvas.textures": {
        "0": "./foo.jpg",
        "1": "./bar.jpg",
        "2": "./foobar.jpg"
    }, 
}
```

**Comment by actarian** [comment]
@TheMasterFX issue has been resolved in latest version `0.2.13`. Thank you for your submission.
