### ISSUE TITLE
Texture samples array does not work

### ISSUE THREAD

**Issue by edap** [actarian/vscode-glsl-canvas#65]
In my workspace settings I have:

```
{
    "glsl-canvas.textures": {
        "0": "./textures/0.png",
        "1": "./textures/1.png",
        "2": "./textures/2.png",
    }
}
```

In my shader I use this uniforms:

```
uniform sampler2D u_tex0;
uniform sampler2D u_tex1;
uniform sampler2D u_tex2;
```

All the 3 samplers show the same image, "./textures/0.png".  It looks like slot 1 and slot 2 are not read, or their content is overwritten by the first texture in glsl-canvas.textures object.

**Comment by actarian** [comment]
Hi @edap correct naming for textures is
`uniform sampler2D u_texture_0;`
`uniform sampler2D u_texture_1; ` 
`uniform sampler2D u_texture_2;`

**Comment by edap** [comment]
I see, thanks.
