### ISSUE TITLE
Can't use local images as textures

### ISSUE THREAD

**Issue by sixclones** [actarian/vscode-glsl-canvas#7]
Hello,

I've try to use texture but when I define one with a path to my computer, it doesn't show anything.

```
{
    "glsl-canvas.textures": {
        "0": "./img/a.jpg",
        "1": "/Users/Me/directory/img/b.jpg",
        "2": "https://thebookofshaders.com/15/hokusai.jpg"
    }
}
```

Textures 0 and 1 doesn't work but 2 is ok.

The `settings.json` is located on `.vscode/settings.json` of my project.

VSCode : 1.26.1
macOS : 10.13.6
glsl-canvas : 0.1.91

**Comment by muukii** [comment]
I have the same issue.
But, I can use an absolute path with `file://`.

**Comment by actarian** [comment]
@sixclones  @muukii  issue has been fixed in latest release. now you can use relative path for textures.

**Comment by sixclones** [comment]
Thanks man ! 👍

**Comment by muukii** [comment]
@actarian Ohhhh! Thank you so much!

**Comment by nzhddemian** [comment]
got the Texture error on macos 12.6 with local files only
