### ISSUE TITLE
"Create one" button to create .glsl editor does'nt do anything

### ISSUE THREAD

**Issue by ErwanBueche** [actarian/vscode-glsl-canvas#8]
I don't really know if this has it's place here but i'll try.
So i'm working with Ubuntu 18.04 and wanted to visualise my webgl canvas in vs code.
I've installed glslCanvas and reloaded my vs code and typed the command "Show glslCanvas" and it opens the window and says there's no active .glsl Editor. The problem is when i click on the button to create one it doesn't do anything. I've tried uninstalling and reinstalling the extension, closing vs code, even rebooting my computer but it doesn't do anything.
As i said i don't really know if this is the right place for that but i haven't found anywhere else.
Thank you for understing.

**Comment by DJLink** [comment]
having the same issue on Windows, can't use it

**Comment by actarian** [comment]
@ErwanBueche @DJLink hi, running Show glslCanvas command should open a small fragment shader on a secondary panel. focusing that panel you should see this.  

![schermata 2018-12-01 alle 15 21 01](https://user-images.githubusercontent.com/1841442/49329358-d64eb680-f57d-11e8-909e-6f2e366b5802.png)

  
If you have problem please submit a more detailed use case.  
system, vscode version, installed extensions, screenshot.  

please run also this command from the commands palette. "Developer: Toggle Developer Tools"  
and copy paste here error messages if found.

**Comment by actarian** [comment]
@ErwanBueche trying to debug on a fresh install of Ubuntu 18.04 in vmware and seems that vscode cannot find the opengl drivers.

`libGL error: unable to load driver: vmwgfx_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: vmwgfx
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast`

To double check try launch this command after `Show glslCanvas`  ->  `Developer: Open Webview Developer Tools`
you should see this error.

`Uncaught TypeError: Cannot read property 'VERTEX_SHADER' of undefined`

but maybe is only a vmware related problem.

**Comment by actarian** [comment]
@ErwanBueche  ok I did solve the webgl issue in Ubuntu removing vscode from the /snap folder and re installing it manually from the .deb file from [here](https://code.visualstudio.com/docs/setup/linux)

`sudo apt install ./code.deb`

after this the extension work as usual.

if you continue to have issue check your OpenGL drivers running this command in terminal 
`glxinfo | grep OpenGL`

**Comment by ChopperLin** [comment]
add these lines in your vscode's "settings.json"

{
    "files.associations": {
        "*.glsl": "glsl"
    },
    "glsl-canvas.autoPreview": true
}
